### ISSUE TITLE
network card can't work.

### ISSUE THREAD

**Issue by JackokieZhao** [MenschLennart/AsusTUFX570GamingPlusWIFI#1]
Hello, I found a problem that the x570 tuf gamiling plus LAN cant't work with your EFI. I don't know the reason.
However, it can work normally in Catalina.

**Comment by MenschLennart** [comment]
I'm using OpenIntelWireless here. Currently the stable branch since  I tried getting better Bluetooth handling and this might be the issue here. But be aware my setup is for Big Sur either. I'm still testing on itlwm.

**Comment by MenschLennart** [comment]
Since this is Kext related. Can't change anything on that really.

**Comment by JackokieZhao** [comment]
Sorry, I haven't show my opinion clearly. I means that the LAN can work well in Catalina but not in Big Sur with your EFI(I have update my system to big sur). I just put your EFI directory in my EFI partion. And, I have another try with the only modification of platforminfo, but,... no wokr...

**Comment by MenschLennart** [comment]
My LAN works perfectly fine. So it can't be EFI related. You changed your BIOS settings also?

**Comment by JackokieZhao** [comment]
Do you mean that your bios is in default configure? I haven't do anythiny on the bios because the LAN works well in pre catalina system. I'll try to make the default configure for the bois again and have a try for your EFI. If it can't work still, I'll report it to you. Thanks...

**Comment by MenschLennart** [comment]
No it's not. You should follow this guide here: 
https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#amd-bios-settings
I don't know which CPU you're using, but you need to adjust some settings in Bios too. Maybe that's why LAN is not probably working in Big Sur for you. But if you have the same board as I do, there must be a mistake somewhere.

**Comment by JackokieZhao** [comment]
The CPU is 3900X, motherboard is x570 gaming plus wifi.

Best regards,

Jackokie（Jiwei） Zhao

------------------------------------------------------------------------------------

Mobile: +86-14751806600/13853203210

Email: jackokie@qq.com
URL: http://www.jackokie.com

Address: School of electronic science and engineering, Nanjing University，

Xianlin Avenue Nanjing No. 163 Electronic Building (Panzhong to floor)
210093


MenschLennart <notifications@github.com> 于2020年11月21日周六 下午9:06写道：

**Comment by MenschLennart** [comment]
So basically same setup. LAN works perfectly fine for me and should for u too. Check BIOS settings.

**Comment by JackokieZhao** [comment]
have you done any setup for the bois? I have closed the Fast boot, CSM,
Serial Port. What's terrible is the restart happenning when the apple login
process bar.

I haven't found the "Secure Boot", "Parallel Port".

Could you please show me your change in BOIS?

Best regards,

Jackokie（Jiwei） Zhao

------------------------------------------------------------------------------------

Mobile: +86-14751806600/13853203210

Email: jackokie@qq.com
URL: http://www.jackokie.com

Address: School of electronic science and engineering, Nanjing University，

Xianlin Avenue Nanjing No. 163 Electronic Building (Panzhong to floor)
210093


MenschLennart <notifications@github.com> 于2020年11月21日周六 下午9:13写道：

**Comment by JackokieZhao** [comment]
Hi, the LAN of my compyter still can't work now. Could you please share your Bois configure with me? It can be exported as a file.
Thanks!

**Comment by MenschLennart** [comment]
Sorry but I can't give long term support on general OpenCore issues here. I do have the same setup as u have and it works just fine for me.
